apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: attendance-system
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "SecureP@ssw0rd123"
  POSTGRES_DB: "attendance_db"
